// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaymentMicroservice.Data;

#nullable disable

namespace PaymentMicroservice.Migrations.SupplierPaymentMigrations
{
    [DbContext(typeof(SupplierPaymentDetailsDbContext))]
    [Migration("20250726161758_InitialCreate_Supplier")]
    partial class InitialCreate_Supplier
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PaymentMicroservice.Domain.SupplierPaymentDetails", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<long>("SortCodeAccountNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("SupplierId");

                    b.ToTable("supplier_payment_details", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
