// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaymentMicroservice.Data;

#nullable disable

namespace PaymentMicroservice.Migrations.PaymentRecordMigrations
{
    [DbContext(typeof(PaymentRecordDbContext))]
    [Migration("20250726161733_InitialCreate_Payment")]
    partial class InitialCreate_Payment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PaymentMicroservice.Domain.PaymentRecord", b =>
                {
                    b.Property<string>("PaymentItemId")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("DatePaid")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Item")
                        .HasColumnType("longtext");

                    b.Property<string>("PaidBy")
                        .HasColumnType("longtext");

                    b.Property<string>("PaymentId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Supplier")
                        .HasColumnType("longtext");

                    b.HasKey("PaymentItemId");

                    b.ToTable("payment_records", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
