// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaymentMicroservice.Data;

#nullable disable

namespace PaymentMicroservice.Migrations
{
    [DbContext(typeof(PaymentDbContext))]
    [Migration("20250725155603_RenamedTable")]
    partial class RenamedTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PaymentMicroservice.Domain.PaymentRecord", b =>
                {
                    b.Property<int>("PaymentItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatePaid")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Item")
                        .HasColumnType("int");

                    b.Property<string>("PaidBy")
                        .HasColumnType("longtext");

                    b.Property<int>("PaymentId")
                        .HasColumnType("int");

                    b.Property<string>("Supplier")
                        .HasColumnType("longtext");

                    b.HasKey("PaymentItemId");

                    b.ToTable("payment_records", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
